FROM node:20-slim

WORKDIR /app

# install dependencies
COPY frontend/package.json frontend/package-lock.json ./
RUN npm install

# copy frontend source
COPY frontend/ .

# start React dev server
CMD ["npm", "start"]